name: 002 Global Resources Deployment

on:
  workflow_run:
    workflows: ["001 Base Deployment"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
  # push:
  #   paths:
  #     - '02global/**'
  #     - '!02global/readme.md'
  
env:
  WORKSPACE: "global"
  FOLDERNAME: "02global"
  REGION: "eu-west-1"
  TERRAFORM_VERSION: "1.3.7"

jobs:
  global_deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: global_deployment
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
    - uses: actions/checkout@v3

    - name: Global Deployment - Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: ${{ env.REGION }}
        role-to-assume: ${{ secrets.ROLE_NAME }}
        role-session-name: "terraform-${{ env.WORKSPACE }}-apply"

    - name: Global Deployment - Install Terraform        
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

    - name: Global Deployment - Verify Terraform version
      run: terraform --version

    - name: Global Deployment - Terraform format
      run: terraform -chdir=$FOLDERNAME fmt

    - name: Global Deployment - Terraform init
      run: terraform -chdir=$FOLDERNAME init -input=false

    - name: Global Deployment - Terraform workspace
      run: terraform -chdir=$FOLDERNAME workspace select $WORKSPACE || terraform -chdir=$FOLDERNAME workspace new $WORKSPACE

    - name: Global Deployment - Terraform validate
      run: terraform -chdir=$FOLDERNAME validate

    - name: Global Deployment - Terraform plan
      run: terraform -chdir=$FOLDERNAME plan -input=false

    - name: Global Deployment - Terraform apply
      run: terraform -chdir=$FOLDERNAME apply -auto-approve -input=false
