name: 101 Deploy Central Website HTML - Dev

on: 
  workflow_dispatch:
   push:
     paths:
       - 'website/site/**'
       - '!website/site/readme.md'

env:
  ENVIRONMENT: "dev"
  REGION: "eu-west-1"
  AWS_KEY: ${{ secrets.AWS_KEY }}
  AWS_SECRET: ${{ secrets.AWS_SECRET }}

jobs:
  update-website:
    runs-on: ubuntu-latest
    #environment: dev
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: ${{ env.REGION }}
        role-to-assume: ${{ secrets.ROLE_NAME }}
        role-session-name: "terraform-${{ env.ENVIRONMENT }}-apply"

    - name: Deploy website to S3 bucket
      run: |
        sed -i 's/(ACCESS_KEY_ID)/$AWS_KEY/g' ./website/site/index.html
        sed -i 's/(SECRET_ACCESS_KEY)/$AWS_SECRET/g' ./website/site/index.html
        sed -i 's/(AWS_REGION)/$REGION/g' ./website/site/index.html
        aws s3 sync ./website/site/ s3://${{ env.ENVIRONMENT }}.brightoncloud-demo.securebubble.xyz --exclude ".git*" --acl public-read --sse AES256 --delete
